_machine_kwds: &machine_kwds
  image: circleci/classic:201808-01

_store_artifacts_kwds: &store_artifacts_kwds
  path: /home/circleci/work/tests

_test_environment: &test_environment
  WORKDIR: /home/circleci/work
  DOCKER_IMAGE: "niflow"

_set_pr_number: &set_pr_number
  name: Set PR number
  command: |
      echo 'export CIRCLE_PR_NUMBER="${CIRCLE_PR_NUMBER:-${CIRCLE_PULL_REQUEST##*/}}"' >> $BASH_ENV
      source $BASH_ENV
      echo $CIRCLE_PR_NUMBER

_build_main_image_py36: &build_main_image_py36
  name: Build main image (py36)
  no_output_timeout: 60m
  command: |
    .circleci/tools/retry_cmd.sh -n 5 -s 15 \
      docker build \
        --rm=false \
        --tag niflow:py36 \
        --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
        --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
        --build-arg VERSION="${CIRCLE_TAG}" /home/circleci/niflow

_build_main_image_py27: &build_main_image_py27
  name: Build main image (py27)
  no_output_timeout: 60m
  command: |
    .circleci/tools/retry_cmd.sh -n 5 -s 15 \
      docker build \
        --rm=false \
        --tag niflow:py27 \
        --build-arg PYTHON_VERSION_MAJOR=2 \
        --build-arg PYTHON_VERSION_MINOR=7 \
        --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
        --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
        --build-arg VERSION="${CIRCLE_TAG}-py27" /home/circleci/niflow

_download_test_data: &_download_test_data
  name: Download test data
  no_output_timeout: 20m
  working_directory: /home/circleci/examples
  environment:
    OSF_NIPYPE_URL: "https://files.osf.io/v1/resources/nefdp/providers/osfstorage"
  command: |
    export DATA_NIPYPE_TUTORIAL_URL="${OSF_NIPYPE_URL}/57f4739cb83f6901ed94bf21"
    curl -sSL --retry 5 --connect-timeout 15 "$DATA_NIPYPE_TUTORIAL_URL" | tar xj

    export DATA_NIPYPE_FSL_COURSE="${OSF_NIPYPE_URL}/57f472cf9ad5a101f977ecfe"
    curl -sSL --retry 5 --connect-timeout 15 "$DATA_NIPYPE_FSL_COURSE" | tar xz

    export DATA_NIPYPE_FSL_FEEDS="${OSF_NIPYPE_URL}/57f473066c613b01f113e7af"
    curl -sSL --retry 5 --connect-timeout 15 "$DATA_NIPYPE_FSL_FEEDS" | tar xz

_prepare_working_directory: &prepare_working_directory
  name: Prepare working directory
  environment: *test_environment
  command: |
    mkdir -p "$WORKDIR"
    chmod -R 777 "$WORKDIR"

_get_codecov: &_get_codecov
  name: Get codecov
  command: |
    pip install --no-cache-dir codecov

_run_codecov_smoke: &_run_codecov_smoke
  name: Run codecov (smoke tests)
  environment: *test_environment
  command: |
    codecov --file $WORKDIR/tests/smoketest*.xml --root "$HOME/nipype" --flags smoketests -e CIRCLE_JOB


version: 2
jobs:

  test_py3_fmri_fsl_spm:
    machine: *machine_kwds
    working_directory: /home/circleci/niflow
    steps:
      - checkout:
          path: /home/circleci/niflow
      - run: *set_pr_number
      - run: *generate_dockerfiles
      - run: *modify_nipype_version
      - run: *get_base_image
      - run: *build_main_image_py36
      - run: *_get_codecov
      - run: *_download_test_data
      - run: *prepare_working_directory
      - run:
          name: Run FSL reuse pipeline (py36)
          no_output_timeout: 40m
          environment: *test_environment
          command: bash -ux /home/circleci/niflow/.circleci/test_py3_fmri_fsl_reuse_linear_l1.sh
      - run:
          name: Run SPM test workflow - 3D inputs (py36)
          no_output_timeout: 40m
          environment: *test_environment
          command: bash -ux /home/circleci/niflow/.circleci/test_py3_fmri_spm_linear_3d.sh
      - run:
          name: Run SPM test workflow - 4D inputs (py36)
          no_output_timeout: 40m
          environment: *test_environment
          command: bash -ux /home/circleci/niflow/.circleci/test_py3_fmri_spm_linear_4d.sh
      - run: *_run_codecov_smoke
      - store_artifacts: *store_artifacts_kwds

  test_py3_fmri_spm_dartel_multiproc:
    machine: *machine_kwds
    working_directory: /home/circleci/niflow
    steps:
      - checkout:
          path: /home/circleci/niflow
      - run: *set_pr_number
      - run: *generate_dockerfiles
      - run: *modify_nipype_version
      - run: *get_base_image
      - run: *build_main_image_py36
      - run: *_get_codecov
      - run: *_download_test_data
      - run: *prepare_working_directory
      - run:
          name: Run SPM DARTEL Level 1 pipeline (py36)
          no_output_timeout: 1h
          environment: *test_environment
          command: bash -ux /home/circleci/niflow/.circleci/test_py3_fmri_spm_dartel_multiproc_l1.sh
      - run:
          name: Run SPM DARTEL Level 2 pipeline (py36)
          no_output_timeout: 30m
          environment: *test_environment
          command: bash -ux /home/circleci/niflow/.circleci/test_py3_fmri_spm_dartel_multiproc_l2.sh
      - run: *_run_codecov_smoke
      - store_artifacts: *store_artifacts_kwds

  test_fmri_spm_nested_fsl_feeds:
    machine: *machine_kwds
    working_directory: /home/circleci/niflow
    steps:
      - checkout:
          path: /home/circleci/niflow
      - run: *set_pr_number
      - run: *generate_dockerfiles
      - run: *modify_nipype_version
      - run: *get_base_image
      - run: *build_main_image_py36
      - run: *build_main_image_py27
      - run: *_get_codecov
      - run: *_download_test_data
      - run: *prepare_working_directory
      - run:
          name: Run SPM Nested Level 1 pipeline (py36)
          no_output_timeout: 1h
          environment: *test_environment
          command: bash -ux /home/circleci/niflow/.circleci/test_py3_fmri_spm_nested_multiproc_l1.sh
      - run:
          name: Run SPM Nested Level 2 pipeline (py27)
          no_output_timeout: 30m
          environment: *test_environment
          command: bash -ux /home/circleci/niflow/.circleci/test_py2_fmri_spm_nested_multiproc_l2.sh
      - run:
          name: Run FSL FEEDS pipeline (py36)
          no_output_timeout: 40m
          environment: *test_environment
          command: bash -ux /home/circleci/niflow/.circleci/test_py3_fmri_fsl_feeds_linear_l1.sh
      - run: *_run_codecov_smoke
      - store_artifacts: *store_artifacts_kwds

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - test_py3_fmri_fsl_spm:
          requires:
            - compare_base_dockerfiles
      - test_py3_fmri_spm_dartel_multiproc:
          requires:
            - compare_base_dockerfiles
      - test_fmri_spm_nested_fsl_feeds:
          requires:
            - compare_base_dockerfiles
